
spring:
  profiles:
    active: local
    
server:
  port: 8080

spring:

  application:
    name: cylinder-tracking-api

  datasource:
    url: jdbc:postgresql://localhost:5432/bic_cylinder_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: ysp551996@gmail.com
    password: nsupurkbubqptpyk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  access-token-secret: ======================BIC=CYLINDERAPP===========================
  access-token-expiration: 900000  # 15 minutes
  refresh-token-secret: ======================BIC=CYLINDERAPP-RefreshToken===========================
  refresh-token-expiration: 604800000 # 7 days

cookie:
  send-as-cookie: false  # Set this to true if you want tokens as HttpOnly cookies, false for response body
  http-only: true
  secure: false
  path: /api
  domain: localhost
  same-site: None


app:
  admin:
    email: ysp551996@gmail.com
